# Generated by Django 5.2.6 on 2025-10-29 01:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # Las tablas Activo, Mantenimiento y Personal ya existen en la base de datos (PostgreSQL).
        # Reemplazamos migrations.CreateModel por migrations.RunPython.noop para marcar la migración como aplicada
        # sin intentar crear las tablas de nuevo.
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),

        # Nota: La migración original CREABA Activo.
        # migrations.CreateModel(
        #     name='Activo',
        #     # ... (resto de campos y options con 'managed': False)
        # ),

        # Nota: La migración original CREABA Mantenimiento.
        # migrations.CreateModel(
        #     name='Mantenimiento',
        #     # ... (resto de campos y options con 'managed': False)
        # ),

        # Nota: La migración original CREABA Personal.
        # migrations.CreateModel(
        #     name='Personal',
        #     # ... (resto de campos y options con 'managed': False)
        # ),

        # --- El resto de tus operaciones (que sí quieres aplicar) se mantienen intactas ---
        
        migrations.AlterField(
            model_name='pago',
            name='id_reserva',
            field=models.ForeignKey(blank=True, db_column='id_reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.IntegerField(help_text='Duración en horas.'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('id_area', 'fecha_res', 'hora_ini')},
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada'), ('vencida', 'Vencida')], max_length=10)),
                ('qr_code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='usuarios.factura'),
        ),
    ]

    # También debes añadir la parte de 'RunPython.noop' aquí si tu código original la eliminó, 
    # para que las migraciones de Activo, Mantenimiento y Personal se salten correctamente.
    # El código de arriba lo hace de forma agrupada al inicio.